[[main]]
  name = "Projetos"
  pageRef = "/projects"
  weight = 10

[[main]]
  name = "Astrofotografia"
  pageRef = "/astrophotography"
  weight = 20

[[main]]
  name = "Misc"
  pageRef = "/misc"
  weight = 30

[[footer]]
  name = "Licença"
  url = "/license"
  weight = 10
