colorScheme = "ocean"
defaultAppearance = "dark"
autoSwitchAppearance = false

showAuthor = true
showBreadcrumbs = true
showDate = true
showReadingTime = true
showTableOfContents = true
showSummary = true
showTaxonomies = true

[homepage]
  layout = "profile"
  showRecent = true
  showRecentItems = 6
  showMoreLink = true
  showMoreLinkDest = "/astrophotography"
  cardView = true
  cardViewScreenWidth = false

[article]
  showDate = true
  showAuthor = true
  showReadingTime = true
  showTableOfContents = true
  showTaxonomies = true
  showWordCount = false
